ESLint check fix + ESLint update
catenax-ng/tx-digital-product-pass pull request #12
Opened 2023-02-24 14:14 UTC by davidzynda

## What this PR changes/adds

1. Script in package.json update so we can run the test locally and ignore some files
2. yaml file update to block the PR when ESLint finds something
3. ESLint fix for all the warnings and errors

2023-02-24 18:54 UTC, saudkhan116 approved these changes

2023-02-27 08:43 UTC, matbmoser commented
I checked and the scss of the components are abstracted, which is good, but I will test it just in case.
Do we need to merge this to pass the QG5?

2023-02-27 08:44 UTC, matbmoser commented
![image](https://user-images.githubusercontent.com/71728767/221515530-fc30f1f2-7e3c-49ff-9a3c-900788a019f6.png)
I would also not use this approach, instead I would include all them in one document called sections.scss

2023-02-27 08:48 UTC, matbmoser requested changes
We are duplicating logic and creating for each components in the passport a file. When the components are in the same view and are sections in this case (no abstraction is possible) we need to include in one single scss style file

2023-02-27 08:48 UTC, matbmoser commented on src/assets/styles/components/passport/sections/batteryComposition.scss
> +.battery-composition {
Add in src/assets/styles/components/passport/sections.scss

2023-02-27 08:48 UTC, matbmoser commented on src/assets/styles/components/passport/sections/contractInformation.scss
> +.contract-information {
Add in src/assets/styles/components/passport/sections.scss

2023-02-27 08:48 UTC, matbmoser commented on src/assets/styles/components/passport/sections/electrochemicalProperties.scss
> +.electrochemical-properties {
Add in src/assets/styles/components/passport/sections.scss

2023-02-27 08:48 UTC, matbmoser commented on src/assets/styles/components/passport/sections/generalInformation.scss
> +.general-information {
Add in src/assets/styles/components/passport/sections.scss

2023-02-27 08:48 UTC, matbmoser commented on src/assets/styles/components/passport/sections/stateOfBattery.scss
> +.stateOfBattery {
Add in src/assets/styles/components/passport/sections.scss

2023-02-27 08:48 UTC, matbmoser commented on src/assets/styles/main.scss
> +@import "components/landing/dashboardTable";
import src/assets/styles/components/passport/sections.scss

2023-02-27 08:52 UTC, davidzynda commented
> 

I don't think it's necessary for QG5 but it's definitely about quality

2023-02-27 14:50 UTC, matbmoser commented
We need to close this pull request to refactor develop

2023-02-27 14:59 UTC, matbmoser commented
we reopen now

2023-03-01 08:20 UTC, closed without merging