chore/cmp-682/api documentation
catenax-ng/tx-digital-product-pass pull request #155
Opened 2023-08-07 14:44 UTC by dsrparracho

# Why we create this PR?
 
To update the GETTING_STARTED.md, SECRETS_MANAGEMENT.md and backend readme.md files with last changes.
 
# What we want to achieve with this PR?
 
To have the API documentation files updated.
 
# What is new?
 
## Updated
- docs\GETTING_STARTED.md file updated
- docs\SECRETS_MANAGEMENT.md file updated
- productpass\readme.md file updated.

## PR Linked to:

| Tickets |
| :---:   |
| [cmp-682](https://jira.catena-x.net/browse/CMP-682) |

2023-08-10 09:03 UTC, matbmoser requested changes

2023-08-10 09:03 UTC, matbmoser commented on docs/GETTING-STARTED.md
>        the [Connector Setup 3](https://github.com/catenax-ng/product-edc/tree/develop/docs#connector-setup).
Change to tractus x, tractus-x edc

2023-08-11 13:19 UTC, saudkhan116 commented
I am currently on Getting Started guide

2023-08-11 14:16 UTC, matbmoser approved these changes

2023-08-11 14:25 UTC, saudkhan116 approved these changes

2023-08-11 14:26 UTC, merged