Feature/cmp 878/refactor backend config: Refactor backend configuration in product helm chart
catenax-ng/tx-digital-product-pass pull request #195
Opened 2023-11-13 15:33 UTC by saudkhan116

# Why we create this PR?
 
Refactor backend configuration in the product helm chart `templates/backend-config.yaml` and values files to disable/hide the app core configuration from the user and only allow user to configure user-related settings as default.
 
# What we want to achieve with this PR?
 
- To have a reference implementation, the backend needs to be configured directly through the `values.yaml` files and not as a fixed yaml payload
- To enable the specific backend configuration from the helm values file to follow good coding practices
 
# What is new?
 
## Updated

| Tickets |
| :---:   |
| [cmp-878](https://jira.catena-x.net/browse/CMP-878) |

2023-11-13 16:14 UTC, matbmoser approved these changes

2023-11-13 16:14 UTC, matbmoser commented on charts/digital-product-pass/values-int.yaml
> +  url: "materialpass.int.demo.catena-x.net"
We needed to get this URL from the ingress configuration

2023-11-13 16:14 UTC, matbmoser commented on charts/digital-product-pass/templates/configmap-backend.yaml
> +        receiverEndpoint: "https://{{ .Values.backend.url }}/endpoint"
Backend url should come from the Ingress to auto configure and not have data redundancy

2023-11-13 17:25 UTC, saudkhan116 commented on charts/digital-product-pass/templates/configmap-backend.yaml
> +        receiverEndpoint: "https://{{ .Values.backend.url }}/endpoint"
We used a variable "hostname" to populate the backend url from the ingress configuration

2023-11-13 17:37 UTC, saudkhan116 commented on charts/digital-product-pass/values-int.yaml
> +  url: "materialpass.int.demo.catena-x.net"
The url now contains the value from ingress

2023-11-28 13:42 UTC, matbmoser requested changes

2023-11-28 13:42 UTC, matbmoser commented on charts/digital-product-pass/values-beta.yaml
> +    clientId: <path:material-pass/data/beta/backend#clientId>
I think the Client ID and the Client Secret could be included in a "oauth" key better then the "edc" configuration
actualy we need them just for the BPN Discovery, EDC Discovery, IRS and not the EDC.

2023-11-28 13:42 UTC, matbmoser commented on charts/digital-product-pass/values-dev.yaml
> +    clientId: <path:material-pass/data/dev/backend#clientId>
same here

2023-11-28 13:42 UTC, matbmoser commented on charts/digital-product-pass/values-int.yaml
> +    clientId: <path:material-pass/data/int/backend#clientId>
same here

2023-11-28 15:07 UTC, matbmoser commented on charts/digital-product-pass/values-dev.yaml
> +      realm: CX-Central
Shall We also include this configuration there?

2023-11-29 08:32 UTC, matbmoser requested changes

2023-11-29 08:32 UTC, matbmoser commented on charts/digital-product-pass/values.yaml
> +    url: ""
We forgot to remove this

2023-11-29 08:32 UTC, matbmoser commented on charts/digital-product-pass/values.yaml
> +    url: ""
I will do it

2023-11-29 09:18 UTC, saudkhan116 commented on charts/digital-product-pass/values.yaml
> +    url: ""
Please do it by yourself whatever you would like to have, thanks 👍

2023-11-29 14:26 UTC, matbmoser approved these changes

2023-11-29 14:27 UTC, matbmoser commented
Ok now it is there and ready. The charts are also updated to the latest version.

2023-11-29 14:29 UTC, merged